direction: down
MongoDB: {
  icon: https://icons.terrastruct.com/dev%2Fmongodb.svg

  User: {
    shape: sql_table
    id: string {constraint: foreign_key}
    is_pregnancy: bool
    blood_pressure: int
    is_diabetes: bool
  }

  pill_history: {
    shape: sql_table
    user_id: uuid {constraint: foreign_key}
    pill_name: string {constraint: foreign_key}
    start_date: Date
    end_date: Date
  }
}

Postgresql: {
  icon: https://icons.terrastruct.com/dev%2Fpostgresql.svg

  User: {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: string
    e_mail: string
    sex: int
    birth_date: Date
  }

  pill_info: {
    shape: sql_table
    item_seq: int {constraint: primary_key}
    name: string
    entp_name: string
    class_name: string
    effect: string
    warning_message: string
    use_method: string
    image_url: string
    taboo_case: array
  }

  mix_taboo: {
    shape: sql_table
    item_seq: int {constraint: foreign_key}
    mixture_item_seq: int {constraint: foreign_key}
    prohibited_content: string
  }

  pill_info.item_seq -> mix_taboo.item_seq
  pill_info.item_seq -> mix_taboo.mixture_item_seq
}

Postgresql.User.id -> MongoDB.User.id: {style: {stroke-dash: 2}}
Postgresql.User.id -> MongoDB.pill_history.user_id: {style: {stroke-dash: 2}}
Postgresql.pill_info.name -> MongoDB.pill_history.pill_name
