direction: down
MongoDB: |json
  User: {
    "id": UUID,
    "is_pregnancy": false,
    "blood_pressure": 1,
    "is_diabetes": false,
    "pill_histories": [{
      "pills": ["item_seq"],
      "start_date": "Date",
      "end_date": "Date",
    },
  ]
|

Postgresql: {
  icon: https://icons.terrastruct.com/dev%2Fpostgresql.svg

  User: {
    shape: sql_table
    id: uuid {constraint: primary_key}
    name: string
    e_mail: string
    sex: int
    birth_date: Date
  }

  pill_info: {
    shape: sql_table
    item_seq: int {constraint: primary_key}
    name: string
    entp_name: string
    class_name: string
    effect: string
    warning_message: string
    use_method: string
    image_url: string
    taboo_case: array
  }

  mix_taboo: {
    shape: sql_table
    item_seq: int {constraint: foreign_key}
    mixture_item_seq: int {constraint: foreign_key}
    prohibited_content: string
  }

  pill_info.item_seq -> mix_taboo.item_seq
  pill_info.item_seq -> mix_taboo.mixture_item_seq
}
