Client: {
  icon: https://icons.terrastruct.com/tech%2F052-smartphone-3.svg
  약력복용정보: {
    shape: document
  }
}

Servers: {
  direction: down
  Oauth2: {
    icon: https://icons.terrastruct.com/social%2F038-google-drive.svg
  }
  OurServer: "2023년 캡스톤 최종_최종" {
    API: {
      Web: {
        Auth
        약학정보
        적합성
      }
      ML: {
        icon: https://icons.terrastruct.com/aws%2FMachine%20Learning%2FMachine-Learning.svg
      }
    }
    DB: {
      shape: cylinder
      User: {
        shape: person
      }
      약: {
        shape: oval
      }
    }
  }
}

Client -> Servers.Oauth2: "Sign up & Sign in"
Client -> Servers.OurServer: request
Client -> Servers.OurServer.API.ML: "약 사진"
Servers.OurServer.API.ML -> Client: "후보군"
Servers.OurServer -> Client: response
Servers.OurServer.API.Web <-> Servers.OurServer.DB: transaction {style.animated: true}
