direction: right
Client: {
  icon: https://icons.terrastruct.com/tech%2F052-smartphone-3.svg
  약력복용정보: {
    shape: document
  }
}

Cralwer: {
  icon: https://icons.terrastruct.com/dev%2Fpython.svg
}
공공데이터 -> Cralwer -> Servers.Postgreql 

Servers: {
  Postgreql: {icon: https://icons.terrastruct.com/dev%2Fpostgresql.svg}
  MongoDB: {icon: https://icons.terrastruct.com/dev%2Fmongodb.svg}
  Cognito: {icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAmazon-Cognito.svg}
  APIGateway: {icon: https://icons.terrastruct.com/aws%2FMobile%2FAmazon-API-Gateway.svg}
  Lambda: {icon: https://icons.terrastruct.com/aws%2FCompute%2FAWS-Lambda.svg}
  APIGateway -> Cognito
  Cognito -> Lambda

  APIGateway <-> MongoDB: transaction
  APIGateway <-> Postgreql: transaction
}
Client <-> Servers.APIGateway: request & response

Client <-> Servers.Cognito: "Sign up & Sign in"
